# Generated by Django 5.0.4 on 2024-04-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookgas',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='connection',
            name='mobilenumber',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connection',
            name='adharno',
            field=models.CharField(max_length=12),
        ),
    ]
