# Generated by Django 5.0.4 on 2024-04-26 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasbookapp', '0002_bookgas_status_connection_mobilenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookgas',
            name='connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gasbookapp.connection'),
            preserve_default=False,
        ),
    ]
