# Generated by Django 5.0.4 on 2024-04-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasbookapp', '0003_bookgas_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookgas',
            old_name='gasbook',
            new_name='cylinder_KG',
        ),
    ]
