# Generated by Django 5.0.4 on 2024-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasbookapp', '0004_rename_gasbook_bookgas_cylinder_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgas',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookgas',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='In Progress', max_length=100),
        ),
        migrations.AlterField(
            model_name='connection',
            name='applieddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
